export const BlogDetails =
[
    {
        id:1,
        href:"https://tighten.com/blog/react-hooks-for-beginners-managing-state",
        data_bg:"https://tighten.com/assets/images/blog/react-hooks-for-beginners-managing-state-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/react-hooks-for-beginners-managing-state-preview-image.png",
        title:"React Hooks for Beginners: Managing State",
        src:"/Blog-Page-img/blog-1-img-1.jpg",
        auth:"Daniel Coulbourne",
        date:"Feb 4",
        time:"6 minute read",
        para:" We’ve been using React at Tighten for almost as long as we’ve been using Vue. In fact, one of our most-read blog post series is an extensive React tutorial by former...",

    },
    {
        id:2,
        href:"https://tighten.com/blog/how-to-train-your-keyboard",
        data_bg:"https://tighten.com/assets/images/blog/how-to-train-your-keyboard-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/how-to-train-your-keyboard-preview-image.png",
        title:"How to Train Your Keyboard",
        src:"/Blog-Page-img/andrew.jpg",
        auth:"Andrew Morgan",
        date:"Dec 17, 2021",
        time:"34 minute read",
        para:" If you’re reading this, odds are you work on a computer. You likely use a combination of your mouse and keyboard to interact with your computer throughout the day. But you're probably also aware that most of the apps you use on a daily basis provide...",

    },
    {
        id:3,
        href:"https://tighten.com/blog/flying-solo-my-experience-as-the-only-designer-at-a-programming-agency",
        data_bg:"https://tighten.com/assets/images/blog/flying-solo-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/flying-solo-preview-image.png",
        title:"Flying Solo",
        src:"/Blog-Page-img/nohemi.jpg",
        auth:"Nohemi Olvera",
        date:"Oct 27, 2021",
        time:"3 minute read",
        para:" Over the last eight years I’ve worked as a designer in many different contexts: non-profits, startups, corporations, and more. I joined Tighten in 2018 as the company’s first full-time designer. Having the opportunity and freedom to develop a...",

    },
    {
        id:4,
        href:"https://tighten.com/blog/a-project-managers-top-tips-for-digital-project-management-success",
        data_bg:"https://tighten.com/assets/images/blog/a-project-managers-top-tips-for-digital-project-management-success-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/a-project-managers-top-tips-for-digital-project-management-success-preview-image.png",
        title:"A Project Manager’s Top Tips",
        src:"/Blog-Page-img/jeanne.jpg",
        auth:"Jeanne Henry",
        date:"Sep 20, 2021",
        time:"8 minute read",
        para:" Just as each workday is a little different, the same can be said about digital projects. Some digital projects are big and require large teams, months of collaboration, and brand new everything to bring them from beginning to end. Some come and go in...",

    },
     {
        id:5,
        href:"https://tighten.com/blog/working-through-a-pandemic",
        data_bg:"https://tighten.com/assets/images/blog/working-through-a-pandemic-thumbnail.png" ,
        background:"https://tighten.com/assets/images/blog/working-through-a-pandemic-thumbnail.png",
        title:"Working Through A Pandemic",
        src:"/Blog-Page-img/marje.jpg",
        auth:"Marje Holmstrom-Sabo",
        date:"May 6, 2021",
        time:"5 minute read",
        para:" At this point, I think the world is in agreement that global pandemics are terrible.  Even with the advantages of already working as a fully remote company, folks at Tighten still struggle with the realities of working through isolation, finding...",

    },
    {
        id:6,
        href:"https://tighten.com/blog/improving-google-maps-performance-on-large-datasets",
        data_bg:"https://tighten.com/assets/images/blog/improving-google-maps-performance-on-large-datasets-thumbnail.png" ,
        background:"https://tighten.com/assets/images/blog/improving-google-maps-performance-on-large-datasets-thumbnail.png",
        title:"Improving Google Maps Performance on Large Datasets",
        src:"/Blog-Page-img/tammy.jpg",
        auth:"Tammy Robinson",
        date:"May 15, 2021",
        time:"9 minute read",
        para:" If you've ever built an app that plots data on a map, you've probably noticed that performance tends to slow down as your dataset grows larger. Zooming out too far causes thousands of map markers to display, slowing your map to a crawl, or perhaps...",

    },
    {
        id:7,
        href:"https://tighten.com/blog/full-text-search-with-meilisearch-and-scout",
        data_bg:"https://tighten.com/assets/images/blog/full-text-search-with-meilisearch-preview-image.jpg" ,
        background:"https://tighten.com/assets/images/blog/full-text-search-with-meilisearch-preview-image.jpg",
        title:"Full-Text Search with MeiliSearch and Laravel Scout",
        src:"/Blog-Page-img/jose.jpg",
        auth:"Jose Soto",
        date:"Feb 1, 2021",
        time:"2 minute read",
        para:"Learn how to add full-text search to your Eloquent models using the free, self-hosted search engine MeiliSearch and Laravel Scout.",

    },
    {
        id:8,
        href:"https://tighten.com/blog/2020-reasons-for-gratitude",
        data_bg:"https://tighten.com/assets/images/blog/2020-reasons-for-gratitude-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/2020-reasons-for-gratitude-preview-image.png",
        title:"Reasons for Gratitude",
        src:"/Blog-Page-img/marje.jpg",
        auth:"Marje Holmstrom-Sabo",
        date:"Dec 22, 2020",
        time:"2 minute read",
        para:" 2020 has been described as many things–unprecedented, a year like no other, a dumpster fire, a train wreck.  It has indeed been a challenging year, for many reasons.Rather than rehashing those challenges, I asked my favorite team to share some of...",

    },
    {
        id:9,
        href:"https://tighten.com/blog/laracon-scholarship-program",
        data_bg:"https://tighten.com/assets/images/blog/laracon-scholarship-program-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/laracon-scholarship-program-preview-image.png",
        title:"The Laravel Community Gathers to Provide Conference Scholarships",
        src:"/Blog-Page-img/marje.jpg",
        auth:"Marje Holmstrom-Sabo",
        date:"Sep 24, 2020",
        time:"3 minute read",
        para:"Late last year, Tighten founders Matt Stauffer and Dan Sheetz were planning how they could contribute positively to the Laravel community.",

    },
    {
        id:10,
        href:"https://tighten.com/blog/the-tighten-test",
        data_bg:"https://tighten.com/assets/images/blog/the-tighten-test-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/the-tighten-test-preview-image.png",
        title:"The Tighten Test: 12 Steps to a Better Team",
        src:"/Blog-Page-img/sara.jpg",
        auth:"Sara Bine",
        date:"Aug 9, 2020",
        time:"12 minute read",
        para:" A modern take on Joel Spolsky’s “The Joel Test: 12 Steps to Better Code” listing 12 qualities we think the best software development teams have in common.",

    },
    {
        id:11,
        href:"https://tighten.com/blog/converting-a-legacy-app-to-laravel",
        data_bg:"https://tighten.com/assets/images/blog/legacy-to-laravel-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/legacy-to-laravel-preview-image.png",
        title:"Legacy to Laravel: How to Modernize an Aging PHP Application",
        src:"/Blog-Page-img/andrew.jpg",
        auth:"Andrew Morgan",
        date:"Jul 28, 2020",
        time:"19 minute read",
        para:"Many of our clients have legacy PHP apps and want to move to Laravel. We’re often asked 'should we rewrite or refactor?' While full rewrites are appealing, they’re also risky. Here’s our approach to gradually refactoring legacy code that lets you start using Laravel right away.",

    },
    {
        id:12,
        href:"https://tighten.com/blog/php-powered-alfred-workflows",
        data_bg:"https://tighten.com/assets/images/blog/php-powered-alfred-workflows-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/php-powered-alfred-workflows-preview-image.png",
        title:"PHP-Powered Alfred 4 Workflows",
        src:"/Blog-Page-img/jose.jpg",
        auth:"Jose Soto",
        date:"Jul 15, 2020",
        time:"4 minute read",
        para:"Did you know you can use your PHP skills to build a powerful Alfred Workflow? Creating custom workflows can allow you to fully utilize the power of Alfred to save time and automate tasks. It's also a lot of fun to share workflows with others....",

    },
    {
        id:13,
        href:"https://tighten.com/blog/making-space-for-brain-stuff",
        data_bg:"https://tighten.com/assets/images/blog/making-space-for-brain-stuff-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/making-space-for-brain-stuff-preview-image.png",
        title:"Making Space for Brain Stuff",
        src:"/Blog-Page-img/marje.jpg",
        auth:"Marje Holmstrom-Sabo",
        date:"Jun 9, 2020",
        time:"6 minute read",
        para:"At Tighten, we want to bring our best selves to work, so that we can bring our best work to our team and clients. In order to do that consistently, we make time and space to care for our brains as well as our bodies.",

    },
    {
        id:14,
        href:"https://tighten.com/blog/your-app-is-a-package-manager",
        data_bg:"https://tighten.com/assets/images/blog/your-app-is-a-package-manager-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/your-app-is-a-package-manager-preview-image.png",
        title:"Your App is a Package Manager",
        src:"/Blog-Page-img/sara.jpg",
        auth:"Sara Bine",
        date:"May 15, 2020",
        time:"7 minute read",
        para:"Keeping code organized, readable, and maintainable is tough, and there's no one-size-fits-all solution. Separating your features into dependencies is a good first step for most applications, resulting in cleaner code without the huge complexity cost of a microservice architecture.",

    },
    {
        id:15,
        href:"https://tighten.com/blog/intro-to-mobile-app-development-with-nativescript-vue",
        data_bg:"https://tighten.com/assets/images/blog/intro-to-mobile-app-development-with-nativescript-vue-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/intro-to-mobile-app-development-with-nativescript-vue-preview-image.png",
        title:"Intro to Mobile App Development with NativeScript-Vue",
        src:"/Blog-Page-img/sara.jpg",
        auth:"Sara Bine",
        date:"Apr 27, 2020",
        time:"6 minute read",
        para:"Learn how to build cross-platform, native mobile apps using familiar Vue.js syntax and Tailwind CSS.",

    },
    {
        id:16,
        href:"https://tighten.com/blog/opting-out-a-simple-solution-for-conditionally-cancelling-laravel-notifications",
        data_bg:"https://tighten.com/assets/images/blog/opting-out-of-laravel-notifications-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/opting-out-of-laravel-notifications-preview-image.png",
        title:"Opting Out: A Simple Solution for Conditionally Cancelling Laravel Notifications",
        src:"/Blog-Page-img/john.jpg",
        auth:"John Bonaccorsi",
        date:"Mar 16, 2020",
        time:"5 minute read",
        para:"The average Laravel app sends between a few and a few dozen notifications to users, but what happens when they want to opt out? With legal regulations like GDPR, it's more important than ever to give users control over the emails they receive.",

    },
    {
        id:17,
        href:"https://tighten.com/blog/adding-commits-to-a-pull-request",
        data_bg:"https://tighten.com/assets/images/blog/pushing-commits-to-another-persons-pr-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/pushing-commits-to-another-persons-pr-preview-image.png",
        title:"Adding Commits to Someone Else's Pull Request",
        src:"/Blog-Page-img/jake.jpg",
        auth:"Jake Bathman",
        date:"Jan 31, 2020",
        time:"2 minute read",
        para:" At Tighten, we do lots of open source work. We even have a whole day every week devoted to it. And, thankfully, we have many members of the open source community contributing pull requests to our projects and packages.But occasionally we have...",

    },
    {
        id:18,
        href:"https://tighten.com/blog/developing-blocker-friendly-websites",
        data_bg:"https://tighten.com/assets/images/blog/developing-blocker-friendly-websites-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/developing-blocker-friendly-websites-preview-image.png",
        title:"Developing Blocker-Friendly Websites",
        src:"/Blog-Page-img/sara.jpg",
        auth:"Sara Bine",
        date:"Jan 10, 2020",
        time:"5 minute read",
        para:" Internet tracking has gotten out of control, and some users are turning to 'blocker' browser extensions to protect themselves. Learn how to adapt your website so these users (and all other users) have a better experience.",

    },
]