export const BlogDetails =
[
    {
        id:1,
        href:"https://tighten.com/blog/react-hooks-for-beginners-managing-state",
        data_bg:"https://tighten.com/assets/images/blog/react-hooks-for-beginners-managing-state-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/react-hooks-for-beginners-managing-state-preview-image.png",
        title:"React Hooks for Beginners: Managing State",
        src:"/Blog-Page-img/blog-1-img-1.jpg",
        auth:"Daniel Coulbourne",
        date:"Feb 4",
        time:"6 minute read",
        para:" We’ve been using React at Tighten for almost as long as we’ve been using Vue. In fact, one of our most-read blog post series is an extensive React tutorial by former...",

    },
    {
        id:2,
        href:"https://tighten.com/blog/how-to-train-your-keyboard",
        data_bg:"https://tighten.com/assets/images/blog/how-to-train-your-keyboard-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/how-to-train-your-keyboard-preview-image.png",
        title:"How to Train Your Keyboard",
        src:"/Blog-Page-img/andrew.jpg",
        auth:"Andrew Morgan",
        date:"Dec 17, 2021",
        time:"34 minute read",
        para:" If you’re reading this, odds are you work on a computer. You likely use a combination of your mouse and keyboard to interact with your computer throughout the day. But you're probably also aware that most of the apps you use on a daily basis provide...",

    },
    {
        id:3,
        href:"https://tighten.com/blog/flying-solo-my-experience-as-the-only-designer-at-a-programming-agency",
        data_bg:"https://tighten.com/assets/images/blog/flying-solo-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/flying-solo-preview-image.png",
        title:"Flying Solo",
        src:"/Blog-Page-img/nohemi.jpg",
        auth:"Nohemi Olvera",
        date:"Oct 27, 2021",
        time:"3 minute read",
        para:" Over the last eight years I’ve worked as a designer in many different contexts: non-profits, startups, corporations, and more. I joined Tighten in 2018 as the company’s first full-time designer. Having the opportunity and freedom to develop a...",

    },
    {
        id:4,
        href:"https://tighten.com/blog/a-project-managers-top-tips-for-digital-project-management-success",
        data_bg:"https://tighten.com/assets/images/blog/a-project-managers-top-tips-for-digital-project-management-success-preview-image.png" ,
        background:"https://tighten.com/assets/images/blog/a-project-managers-top-tips-for-digital-project-management-success-preview-image.png",
        title:"A Project Manager’s Top Tips",
        src:"/Blog-Page-img/jeanne.jpg",
        auth:"Jeanne Henry",
        date:"Sep 20, 2021",
        time:"8 minute read",
        para:" Just as each workday is a little different, the same can be said about digital projects. Some digital projects are big and require large teams, months of collaboration, and brand new everything to bring them from beginning to end. Some come and go in...",

    },
     {
        id:5,
        href:"https://tighten.com/blog/working-through-a-pandemic",
        data_bg:"https://tighten.com/assets/images/blog/working-through-a-pandemic-thumbnail.png" ,
        background:"https://tighten.com/assets/images/blog/working-through-a-pandemic-thumbnail.png",
        title:"Working Through A Pandemic",
        src:"/Blog-Page-img/marje.jpg",
        auth:"Marje Holmstrom-Sabo",
        date:"May 6, 2021",
        time:"5 minute read",
        para:" At this point, I think the world is in agreement that global pandemics are terrible.  Even with the advantages of already working as a fully remote company, folks at Tighten still struggle with the realities of working through isolation, finding...",

    },
    {
        id:6,
        href:"https://tighten.com/blog/improving-google-maps-performance-on-large-datasets",
        data_bg:"https://tighten.com/assets/images/blog/improving-google-maps-performance-on-large-datasets-thumbnail.png" ,
        background:"https://tighten.com/assets/images/blog/improving-google-maps-performance-on-large-datasets-thumbnail.png",
        title:"Improving Google Maps Performance on Large Datasets",
        src:"/Blog-Page-img/tammy.jpg",
        auth:"Tammy Robinson",
        date:"May 15, 2021",
        time:"9 minute read",
        para:" If you've ever built an app that plots data on a map, you've probably noticed that performance tends to slow down as your dataset grows larger. Zooming out too far causes thousands of map markers to display, slowing your map to a crawl, or perhaps...",

    },
]