import React,{useState} from 'react';
import Head from 'next/head'
import styled from 'styled-components';
import Footer from '../components/Footer';
import FooterCard from '../components/FooterCard';
import Form from '../components/Form';
import FormSuccess from '../components/FormSuccess';

export default function Contact() {
  const [isSubmitted, setIsSubmitted] = useState(false);

    function formSubmit(e)
    {
        console.log({e});
        setIsSubmitted(true);
    }
  return (
    <>
      <Head>
        <title>Contact Us | Geexu</title>
        <link rel="icon" 
              href="/header-img/favicon.png"
              type="image/x-icon"              
        />
        <meta charset="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* <!-- Mono font link --> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@700&family=Source+Serif+Pro:wght@300&display=swap"
          rel="stylesheet"
        />
        {/* <!-- mono font link end here --> */}

        {/* <!-- Serif font link --> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="css/style.css" />
        {/* <!-- fontawsome link Start here --> */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        <script
          type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        ></script>
        <script
          nomodule
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        ></script>
        {/* <!-- fontawsome link End here --> */}

        {/* <!-- Tailwind Css Script Tag Start Here --> */}

        <script src="https://cdn.tailwindcss.com"></script>
        {/* <!-- Taiwind Css Script Tag End Here --> */}
      </Head>
      
      
      {/* {!isSubmitted ? (<Form formSubmit={formSubmit}/>) : (<FormSuccess/>)} */}
      {!isSubmitted ? (<Form formSubmit={formSubmit}/>) : (window.alert(`Thank You!!`))}
      
      
    {/* <Form/> */}
      
    </>
  );
}




// import Head from 'next/head'


// export default function About() {
//     return (
//       <>
//         <Head>
//           <title>Create Next App</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
        
//         <h1>About</h1>
//       </>
//     )
//   }
  
  
 
