import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from './about'
import Link from 'next/link'
import Hero from './home'
import Script from 'next/script'


export default function Home() {
  return (
    <div >
      <Head>
        <title>
          Tighten | Software Development</title>
        <meta charset="UTF-8" />
        <link
          rel="shortcut icon"
          href="/header-img/favicon.png"
          type="image/x-icon"
        />

        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <!-- Font Link Goes Here --> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />

        <script
          defer=""
          src="https://tighten.com/assets/build/js/main.js?id=b0b646e36cc5d7106b59"
        ></script>

        <script src="https://cdn.tailwindcss.com"></script>
        {/* <script>
                tailwind.config = {
                  theme: {
                    extend: {
                      fontFamily: {
                        sans: ['Inter', 'sans-serif'],
                      },
                    }
                  }
                }
              </script> */}

        {/* <!-- Fontawsome Link Start Here --> */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        <script type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js">

        </script>
        <script
          nomodule
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        ></script>

        {/* <!-- Tailwind Css Script Tag Here--> */}
        <script src="https://cdn.tailwindcss.com"></script>

        {/* <!-- Slick Slider Start Link Start Here --> */}
        <link
          // href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css"
          rel="stylesheet"
        />
        <link
          // href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" />
        {/* <!-- Slick Slider End Link End Here --> */}

        {/* Link for AOS library */}
        <link rel="stylesheet" href="bower_components/aos/dist/aos.css" />
        {/* script for AOS library */}
        <script src="bower_components/aos/dist/aos.js"></script>
        <script>
          AOS.init();
        </script>





        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}

      </Head>
      <Hero />
      {/* <h1>home page</h1> */}
      {/* <Image src='/logo.png' width='10px' height= '10px'/> */}
      {/* <Image URL=""/> src="/assets/images/header-img/logo.png"*/}
      {/* <Image url=''  height='100px' width='100px' alt='logo'/> */}
      
    </div>
  )
}
