export const TeamDetails=[
    {
        id:1,
        image:"/Team-Page-img/1.jpg",
        alt:"Dan Sheetz",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Dan \n Sheetz",
        para:"partner + MANAGING DIRECTOR",
        head2:"featured contributions",
        head3:"The Great Tighten Ex...",
        para2:"writter",
        head4:"Tighten Manifesto",
        para3:"writter",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Dan \n Sheetz",
        para5:"partner + MANAGING DIRECTOR",

    },
     {
        id:2,
        image:"/Team-Page-img/2.jpg",
        alt:"Matt Stauffer",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Matt \n Stauffer",
        para:"partner + TECHNICAL DIRECTOR",
        head2:"featured contributions",
        head3:"The Great Tighten Ex...",
        para2:"writter",
        head4:"Tighten Manifesto",
        para3:"writter",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Matt Stauffer",
        para5:"partner + TECHNICAL DIRECTOR",

    },
    {
        id:3,
        image:"/Team-Page-img/3.jpg",
        alt:"Alison Krik",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Alison \n Krik",
        para:"Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Alison \n Krik",
        para5:"Programer",

    },
    {
        id:4,
        image:"/Team-Page-img/4.jpg",
        alt:"Andrew Morgen",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Andrew Morgen",
        para:"Lead Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Andrew Morgen",
        para5:"Lead Programer",

    },
    {
        id:5,
        image:"/Team-Page-img/5.jpg",
        alt:" Anna Youngyeun",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Anna Youngyeun",
        para:"Apprentice Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Anna Youngyeun",
        para5:"Apprentice Programer",

    },
    {
        id:6,
        image:"/Team-Page-img/6.jpg",
        alt:" Anna Shevlin",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Anna Shevlin",
        para:"Operation Coordinatior",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Anna Shevlin",
        para5:"Operation Coordinatior",

    },
    
    {
        id:7,
        image:"/Team-Page-img/7.jpg",
        alt:" Anthony Clark",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Anthony Clark",
        para:"Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Anthony Clark",
        para5:"Programer",

    },
    {
        id:8,
        image:"/Team-Page-img/8.jpg",
        alt:"  Cenitoria Melton",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"  Cenitori Melton",
        para:"Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"  Cenitor Melton",
        para5:"Programer",

    },
    {
        id:9,
        image:"/Team-Page-img/9.jpg",
        alt:" Chirs Trombley",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Chirs Trombley",
        para:"Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Chirs Trombley",
        para5:"Programer",

    },
    {
        id:10,
        image:"/Team-Page-img/10.jpg",
        alt:" Dave Hicking",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Dave Hicking",
        para:"Head of Client Service",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Dave Hicking",
        para5:"Head of Client Service",

    },
    {
        id:11,
        image:"/Team-Page-img/11.jpg",
        alt:" Jacob Baker-Kretzmer",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Jacob Baker-Kretzmer",
        para:"Lead Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Jacob Baker-Kretzmer",
        para5:"Lead Programer",

    },
    {
        id:12,
        image:"/Team-Page-img/12.jpg",
        alt:" Jack Bathman",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Jack Bathman",
        para:" Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Jack Bathman",
        para5:" Programer",

    },
    {
        id:13,
        image:"/Team-Page-img/13.jpg",
        alt:" Jamison valenta",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Jamison valenta",
        para:" Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Jamison valenta",
        para5:" Programer",

    },
    {
        id:14,
        image:"/Team-Page-img/14.jpg",
        alt:"Jeanne Henry",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"Jeanne Henry",
        para:" Senior Project Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Jeanne Henry",
        para5:" Senior Project Programer",

    },
     {
        id:15,
        image:"/Team-Page-img/15.jpg",
        alt:"John Bonaccorsi",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"John Bonaccorsi",
        para:" Lead Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"John Bonaccorsi",
        para5:" Lead Programer",

    },
     {
        id:16,
        image:"/Team-Page-img/16.jpg",
        alt:" Keith Damiani",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Keith Damiani",
        para:" Principal Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Keith Damiani",
        para5:" Principal Programer",

    },
    {
        id:17,
        image:"/Team-Page-img/17.jpg",
        alt:" Kristin Collins",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Kristin Collins",
        para:" Lead Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Kristin Collins",
        para5:" Lead Programer",

    },
    {
        id:18,
        image:"/Team-Page-img/18.jpg",
        alt:" Marcus Moore",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Marcus Moore",
        para:"Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Marcus Moore",
        para5:"Programer",

    },
     {
        id:19,
        image:"/Team-Page-img/19.jpg",
        alt:" Marcy Acevedo",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Marcy Acevedo",
        para:" Associate Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Marcy Acevedo",
        para5:" Associate Programer",

    },
    {
        id:20,
        image:"/Team-Page-img/20.jpg",
        alt:"Marje Holmstrom-Sabo",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"Marje Holmstrom-Sabo",
        para:" Associate Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Marje Holmstrom-Sabo",
        para5:" Associate Programer",

    },
     {
        id:21,
        image:"/Team-Page-img/21.jpg",
        alt:"Nathan Morgen",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"Nathan Morgen",
        para:"Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Nathan Morgen",
        para5:"Programer",

    },
    {
        id:22,
        image:"/Team-Page-img/22.jpg",
        alt:"Nohemi Olvera",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"Nohemi Olvera",
        para:"Designer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Nohemi Olvera",
        para5:"Designer",

    },
    {
        id:23,
        image:"/Team-Page-img/23.jpg",
        alt:"Rissa Jackson",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"Rissa Jackson",
        para:"Apprentice Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Rissa Jackson",
        para5:"Apprentice Programer",

    },
    {
        id:24,
        image:"/Team-Page-img/24.jpg",
        alt:"Sara Bine",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:"Sara Bine",
        para:"Lead Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:"Sara Bine",
        para5:"Lead Programer",

    },
    {
        id:25,
        image:"/Team-Page-img/25.jpg",
        alt:" Shawn Jones",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Shawn Jones",
        para:" Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Shawn Jones",
        para5:" Programer",

    },
    {
        id:26,
        image:"/Team-Page-img/26.jpg",
        alt:" Tammy Robinson",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Tammy Robinson",
        para:" Lead Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Tammy Robinson",
        para5:" Lead Programer",

    },
    {
        id:27,
        image:"/Team-Page-img/27.jpg",
        alt:" Tony Messias",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Tony Messias",
        para:" Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Tony Messias",
        para5:" Programer",

    },
    {
        id:28,
        image:"/Team-Page-img/28.jpg",
        alt:" Zuzana Kunckova",
        title:"PARTNER + TECHNICAL DIRECTOR",
        head:" Zuzana Kunckova",
        para:" Programer",
        head2:"featured contributions",
        head3:"Nova Stripe",
        para2:"contributor",
        head4:"PHP Release",
        para3:"contributor",
        head5:"Filed Goal",
        para4:"contributor",
        head6:" Zuzana Kunckova",
        para5:" Programer",

    },
    
    
]